# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.10.0'
  displayName: 'Install Node.js'

- task: DownloadSecureFile@1
  name: envFile
  displayName: 'Download .env file'
  inputs:
    secureFile: '.env'

- script: |
    mv $(envFile.secureFilePath) .
    ls -al
    npm install --legacy-peer-deps --no-audit
    npm install @playwright/test --legacy-peer-deps --no-audit
    npx playwright install
    npm run test:e2e
  displayName: 'E2E Test'
